# generated by datamodel-codegen:
# datamodel-codegen --input <json> --input-file-type json --output-model-type dataclasses.dataclass --output training_session.py

from dataclasses import dataclass
from typing import Any


@dataclass
class Identifier:
    id: str


@dataclass
class PhysicalInformation:
    modified: str
    created: str
    birthday: str
    sex: str
    weightKg: float
    heightCm: int
    vo2Max: int
    trainingBackground: str
    weeklyRtSum: float
    functionalThresholdPower: int
    weightSource: str
    maximumAerobicPower: int
    maximumAerobicSpeedKmh: float


@dataclass
class Application:
    name: str


@dataclass
class Sport:
    id: str


@dataclass
class Product:
    modelName: str


@dataclass
class TrainingLoadReport:
    muscleLoad: float
    cardioLoadInterpretation: str
    muscleLoadInterpretation: str
    calculationTime: str
    perceivedLoadInterpretation: str


@dataclass
class Statistic:
    type: str
    avg: float
    max: float


@dataclass
class Statistics:
    statistics: list[Statistic]


@dataclass
class Zone1:
    lowerLimit: float
    higherLimit: float
    inZone: int | None = None
    distanceMeters: float | None = None


@dataclass
class Zone:
    type: str
    zones: list[Zone1]


@dataclass
class Sample:
    type: str
    intervalMillis: int
    values: list[float | str]


@dataclass
class Samples:
    samples: list[Sample]


@dataclass
class WayPoint:
    longitude: float
    latitude: float
    elapsedMillis: int | None = None


@dataclass
class Route:
    wayPoints: list[WayPoint]
    startTime: str


@dataclass
class TransitionRoute:
    wayPoints: list[WayPoint]
    startTime: str


@dataclass
class Routes:
    route: Route
    transitionRoute: TransitionRoute


@dataclass
class PauseTime:
    startTime: str
    endTime: str


@dataclass
class Exercise:
    identifier: Identifier
    created: str
    modified: str
    startTime: str
    stopTime: str
    durationMillis: int
    distanceMeters: float
    latitude: float
    longitude: float
    timezoneOffsetMinutes: int
    sport: Sport
    strengthTrainingResults: dict[str, Any]
    trainingLoadReport: TrainingLoadReport
    laps: dict[str, Any]
    statistics: Statistics
    zones: list[Zone]
    samples: Samples
    routes: Routes
    pauseTimes: list[PauseTime]


@dataclass
class TrainingSession:
    identifier: Identifier
    created: str
    modified: str
    startTime: str
    stopTime: str
    latitude: float
    longitude: float
    durationMillis: int
    distanceMeters: float
    timezoneOffsetMinutes: int
    physicalInformation: PhysicalInformation
    application: Application
    sport: Sport
    product: Product
    exercises: list[Exercise]
    trainingLoadReport: TrainingLoadReport
