[pytest]
addopts = -s
console_output_style = progress
filterwarnings = ignore::DeprecationWarning
log_cli = True
markers =
  context
  db
  file
minversion = 8.0
testpaths = test
python_files =
  test_activity.py
  test_activity_types.py
  test_application.py
  test_core.py
  test_db.py
  test_keywords.py
  test_resources.py
  test_streams.py
  test_uid.py
  test_utils.py
