[pytest]
addopts = -s
console_output_style = progress
filterwarnings = ignore::DeprecationWarning
log_cli = True
log_cli_level = info
markers =
  context
  db
  file
  resource_type
  service
minversion = 8.0
testpaths = test
python_files = test_*.py
