# generated by datamodel-codegen:
# datamodel-codegen --input <json> --input-file-type json --output-model-type dataclasses.dataclass --output account_profile.py

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class AccountProfile:
    exportVersion: str
    favouriteSports: list[Any]
    countryCode: str
    city: str
