# generated by datamodel-codegen:
# datamodel-codegen --input account-data-*.json --input-file-type json --output-model-type dataclasses.dataclass --output account_data.py

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class PhysicalInformation:
    sex: str
    birthday: str
    height__cm: float
    weight__kg: float
    trainingBackground: str
    sleepGoal: str
    typicalDay: str
    speedCalibrationOffset: float


@dataclass
class LinkedApplication:
    name: str
    url: str
    active: bool
    registered: str
    lastLogin: str
    oauthScopes: list[str]


@dataclass
class Settings:
    firstDayOfWeek: str
    measurementUnit: str
    dateFormat: str
    dateSeparator: str
    timeFormat: str
    timeFormatSeparator: str
    timeZone: str
    language: str
    flowLanguage: str
    newsletter: str
    newFollower: str
    receivedInvitation: str
    newComment: str
    guidanceOrArticles: str
    sessionLiked: str
    activitySummaryLiked: str
    activitySummaryCommented: str
    myCommentCommented: str
    clubCommunication: str


@dataclass
class AccountData:
    exportVersion: str
    username: str
    firstName: str
    lastName: str
    physicalInformation: PhysicalInformation
    linkedApplications: list[LinkedApplication]
    linkedOrganisations: list[Any]
    settings: Settings
