# generated by datamodel-codegen:
# datamodel-codegen --input products-devices-*.json --input-file-type json --output-model-type dataclasses.dataclass --output products_devices.py

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class Setting:
    name: str
    value: str


@dataclass
class Device:
    name: str
    deviceId: str
    deviceUuid: str
    registered: str
    settings: list[Setting]


@dataclass
class Products:
    exportVersion: str
    devices: list[Device]
    archivedDevices: list[Any]
    productRegistrationEvents: list[Any]
