# generated by datamodel-codegen:
#   filename:  training-session-2026-03-04-0e0c90df.json
#   timestamp: 2026-03-12T06:47:21+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class Identifier:
    id: str | None = None


@dataclass
class PhysicalInformation:
    modified: str | None = None
    created: str | None = None
    birthday: str | None = None
    sex: str | None = None
    weightKg: float | None = None
    heightCm: int | None = None
    maximumHeartRate: int | None = None
    restingHeartRate: int | None = None
    aerobicThreshold: int | None = None
    anaerobicThreshold: int | None = None
    vo2Max: int | None = None
    trainingBackground: str | None = None
    typicalDay: str | None = None
    weeklyRtSum: float | None = None
    functionalThresholdPower: int | None = None
    weightSource: str | None = None
    sleepGoalMinutes: int | None = None
    maximumAerobicPower: int | None = None
    maximumAerobicSpeedKmh: float | None = None


@dataclass
class Application:
    name: str | None = None


@dataclass
class Sport:
    id: str | None = None


@dataclass
class Product:
    modelName: str | None = None


@dataclass
class TrainingLoadReport:
    cardioLoad: float | None = None
    muscleLoad: float | None = None
    cardioLoadInterpretation: str | None = None
    muscleLoadInterpretation: str | None = None
    calculationTime: str | None = None
    perceivedLoadInterpretation: str | None = None


@dataclass
class Statistic:
    type: str | None = None
    avg: float | None = None
    max: float | None = None
    min: float | None = None


@dataclass
class Statistics:
    statistics: list[Statistic] | None = None


@dataclass
class AutoLap:
    splitTimeMillis: int | None = None
    durationMillis: int | None = None
    distanceMeters: float | None = None
    ascentMeters: float | None = None
    descentMeters: float | None = None
    statistics: Statistics | None = None


@dataclass
class Laps:
    autoLaps: list[AutoLap] | None = None


@dataclass
class Statistic1:
    type: str | None = None
    min: float | None = None
    avg: float | None = None
    max: float | None = None


@dataclass
class Statistics1:
    statistics: list[Statistic1] | None = None


@dataclass
class Zone1:
    lowerLimit: float | None = None
    higherLimit: float | None = None
    inZone: int | None = None
    distanceMeters: float | None = None


@dataclass
class Zone:
    type: str | None = None
    zones: list[Zone1] | None = None


@dataclass
class Sample:
    type: str | None = None
    intervalMillis: int | None = None
    values: list[float | str] | None = None


@dataclass
class RrSample:
    durationMillis: int | None = None
    offline: bool | None = None


@dataclass
class Samples:
    samples: list[Sample] | None = None
    rrSamples: list[RrSample] | None = None


@dataclass
class WayPoint:
    longitude: float | None = None
    latitude: float | None = None
    altitude: float | None = None
    elapsedMillis: int | None = None


@dataclass
class Route:
    wayPoints: list[WayPoint] | None = None
    startTime: str | None = None


@dataclass
class Routes:
    route: Route | None = None


@dataclass
class PauseTime:
    startTime: str | None = None
    endTime: str | None = None


@dataclass
class Exercise:
    identifier: Identifier | None = None
    created: str | None = None
    modified: str | None = None
    startTime: str | None = None
    stopTime: str | None = None
    durationMillis: int | None = None
    distanceMeters: float | None = None
    calories: int | None = None
    fatPercentage: int | None = None
    recoveryTimeMillis: str | None = None
    carboPercentage: int | None = None
    proteinPercentage: int | None = None
    latitude: float | None = None
    longitude: float | None = None
    ascentMeters: float | None = None
    descentMeters: float | None = None
    timezoneOffsetMinutes: int | None = None
    sport: Sport | None = None
    strengthTrainingResults: dict[str, Any] | None = None
    trainingLoadReport: TrainingLoadReport | None = None
    laps: Laps | None = None
    statistics: Statistics1 | None = None
    zones: list[Zone] | None = None
    samples: Samples | None = None
    routes: Routes | None = None
    pauseTimes: list[PauseTime] | None = None


@dataclass
class DownHill:
    downhillNumber: int | None = None
    descentMeters: float | None = None
    avgDeclinePercent: float | None = None


@dataclass
class UpHill:
    uphillNumber: int | None = None
    ascentMeters: float | None = None
    avgInclinePercent: float | None = None


@dataclass
class Hill:
    type: str | None = None
    startTime: str | None = None
    endTime: str | None = None
    downHill: DownHill | None = None
    distanceMeters: int | None = None
    maxSpeedKmh: float | None = None
    avgSpeedKmh: float | None = None
    startAltitudeMeters: float | None = None
    endAltitudeMeters: float | None = None
    avgHrBpm: int | None = None
    maxHrBpm: int | None = None
    duration: int | None = None
    avgCadence: int | None = None
    maxCadence: int | None = None
    avgPower: int | None = None
    maxPower: int | None = None
    upHill: UpHill | None = None


@dataclass
class HillSplits:
    startTime: str | None = None
    endTime: str | None = None
    totalUphillDistanceMeters: int | None = None
    totalDownhillDistanceMeters: int | None = None
    totalUphillCount: int | None = None
    totalDownhillCount: int | None = None
    hills: list[Hill] | None = None


@dataclass
class TrainingSession:
    identifier: Identifier | None = None
    created: str | None = None
    modified: str | None = None
    startTime: str | None = None
    stopTime: str | None = None
    name: str | None = None
    deviceId: str | None = None
    latitude: float | None = None
    longitude: float | None = None
    durationMillis: int | None = None
    distanceMeters: float | None = None
    calories: int | None = None
    trainingBenefit: str | None = None
    carboPercentage: int | None = None
    fatPercentage: int | None = None
    proteinPercentage: int | None = None
    recoveryTimeMillis: str | None = None
    hrMax: int | None = None
    hrAvg: int | None = None
    timezoneOffsetMinutes: int | None = None
    physicalInformation: PhysicalInformation | None = None
    application: Application | None = None
    sport: Sport | None = None
    product: Product | None = None
    exercises: list[Exercise] | None = None
    hillSplits: HillSplits | None = None
    trainingLoadReport: TrainingLoadReport | None = None
