from tracs.activity_types import ActivityTypes

BASE_URL = 'https://www.strava.com'

TYPES = {
	'AlpineSki': ActivityTypes.ski,
	'BackcountrySki': ActivityTypes.xcski_backcountry,
	'Canoeing': ActivityTypes.canoe,
	'Crossfit': ActivityTypes.crossfit,
	'EBikeRide': ActivityTypes.bike_ebike,
	'Elliptical': ActivityTypes.other,
	'Golf': ActivityTypes.golf,
	'Handcycle': ActivityTypes.bike_hand,
	'Hike': ActivityTypes.hiking,
	'IceSkate': ActivityTypes.ice_skate,
	'InlineSkate': ActivityTypes.inline_skate,
	'Kayaking': ActivityTypes.kayak,
	'Kitesurf': ActivityTypes.kitesurf,
	'NordicSki': ActivityTypes.xcski,
	'Ride': ActivityTypes.bike,
	'RockClimbing': ActivityTypes.climb,
	'RollerSki': ActivityTypes.rollski,
	'Rowing': ActivityTypes.row,
	'Run': ActivityTypes.run,
	'Sail': ActivityTypes.sail,
	'Skateboard': ActivityTypes.skateboard,
	'Snowboard': ActivityTypes.snowboard,
	'Snowshoe': ActivityTypes.snowshoe,
	'Soccer': ActivityTypes.soccer,
	'StairStepper': ActivityTypes.other,
	'StandUpPaddling': ActivityTypes.paddle_standup,
	'Surfing': ActivityTypes.surf,
	'Swim': ActivityTypes.swim,
	'Velomobile': ActivityTypes.other,
	'VirtualRide': ActivityTypes.bike_ergo,
	'VirtualRun': ActivityTypes.run_ergo,
	'Walk': ActivityTypes.walk,
	'WeightTraining': ActivityTypes.gym,
	'Wheelchair': ActivityTypes.other,
	'Windsurf': ActivityTypes.surf_wind,
	'Workout': ActivityTypes.gym,
	'Yoga': ActivityTypes.yoga,
}
